---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
    yamllint .
    ansible-lint
    flake8
platforms:
  - name: ssl-certificate-c7
    image: centos:7
  - name: ssl-certificate-u1604
    image: ubuntu:16.04
provisioner:
  name: ansible
  lint:
    name: ansible-lint
  inventory:
    host_vars:
      ssl-certificate-u1604:
        ssl_certificate_intermediate_content: |
            {{ lookup('file', 'intermediate.pem') }}
verifier:
  name: testinfra