---
- name: Converge
  hosts: all
  roles:
    - role: ansible-role-ssl-certificate

  handlers:
    - name: Create file when ssl certificate changed
      listen: ssl certificate changed
      # Use file so that we get an error if the handler is triggered during
      # the idempotence check
      file:
        path: /tmp/ssl-certificate-changed
        state: touch
        mode: 0644
